version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "8080:80"
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - ./client:/app
      - /app/node_modules
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
